### ISSUE TITLE
sofle rgb guide needs more details

### ISSUE THREAD

**Issue by anishp55** [keyhive/build_guides#9]
i am building the sofle rgb as we speak.  there needs to be more details on flashing the controllers, and on the assembly of the finished PCB + plates.  i am probably doing something wrong, but i can't get the switches to say in place.  if i was to angry press any keys  they would pop out....  also there are different sized standoffs included with the kit and no indications on  what standoffs/spaces should be used in what locations.

**Comment by anishp55** [comment]
the switch plate that is shipped is too thick as well.  i cannot use this keyboard without the switches popping out because they are not locked in place.

**Comment by filoxo** [comment]
Typically speaking, these steps are intuitive. My process is: 

- insert four switches in "four corners", basically anywhere where they'll stay in place to help me align the rest
- insert a tool of some sort (flathead screwdriver or tweezers) in between the plate and the pcb to help keep it in place while exerting downward force
- insert the remaining switches in place
- move the tool out of the way as needed so that you can insert the switches

If the switches are a tiny bit looser in the plate and it won't "stay up" while exerting downward force, try this instead:

- install the standoffs onto the plate
- lay the plate over top of the pcb and hold in hand
- insert the switches into the pcb (while not worrying about making sure they're secured into the plate)
- once all the switches are in place, put it down on hard flat surface with the standoffs holding everything up
- gently but firmly push down on all the switches so that they "click into" the plate

There isn't a single way to do this, and if it were possible we'd try to cover all the use cases but that is a tough thing to do. And now that you've highlighted an area where these instructions could be helpful we can reuse this content as instructions to help other people. Yay for open source! 

Regarding the standoffs, there should only be four that are longer. Those are used for the OLED covers. The rest of them are used for the plates.

If you found that one or the other technique was better for you, please feel free to share and we can include those instructions in the build guide. Because I feel that your question has been sufficiently answered, I'm going to go ahead and close this issue. Feel free to ask any additional questions though.

**Comment by anishp55** [comment]
my kit had 3 long standoffs and about 12 of the short ones and about 20 screws....
